-- Create the search_logs table
create table public.search_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  product_name text not null,
  exporter_hs text,
  description text,
  country_of_origin text,
  candidates jsonb
);

-- Set up Row Level Security (RLS)
-- This is important if you are using the 'Anon' key from the client or backend.
alter table public.search_logs enable row level security;

-- Policy to allow anyone (anon) to insert logs
-- (Adjust this if you only want authenticated users or service_role to insert)
create policy "Enable insert for all users" 
on public.search_logs 
for insert 
with check (true);

-- Policy to allow viewing logs (optional, for debugging)
create policy "Enable read for all users" 
on public.search_logs 
for select 
using (true);

-- Add descriptions for MCP (Model Context Protocol) discovery
comment on table public.search_logs is 'Logs of HTS code searches performed by users, including input parameters and LLM-generated candidates.';
comment on column public.search_logs.id is 'Unique identifier for the search log entry.';
comment on column public.search_logs.created_at is 'Timestamp when the search was performed.';
comment on column public.search_logs.product_name is 'Name of the product being searched.';
comment on column public.search_logs.exporter_hs is 'Optional HS code provided by the exporter (e.g., from Korea).';
comment on column public.search_logs.description is 'Detailed description of the product.';
comment on column public.search_logs.country_of_origin is 'Country where the product was manufactured.';
comment on column public.search_logs.candidates is 'JSONB array containing the list of HTS candidates proposed by the LLM.';
